### PR TITLE
Noahcoder11 branch

### PR DESCRIPTION
**Pull request by noahcoder11**
Create preliminary books page with cards for each book in a given object/dictionary database.

### CODE REVIEW

**Comment by ParthJohri** [comment]
There is a minor bug when I hover over a card. The background image also moves!
Make that right and rest. 
Everything is perfect! Great Work!
I will merge it after the problem is resolved.

**Comment by noahcoder11** [comment]
On firefox, it does not move for me. What browser is it happening on? (so I can use that one for fixing)

**Comment by ParthJohri** [comment]
> On firefox, it does not move for me. What browser is it happening on? (so I can use that one for fixing)

On Google Chrome.

**Comment by noahcoder11** [comment]
I fixed it, I just had to remove width and translation, and simply replace with 'scale: 1.1'

**Comment by noahcoder11** [comment]
Might be good to add another category attribute to the books in the list though to put them in different genres for recommendation and such if it will eventually be an account based system

**Comment by ParthJohri** [comment]
Great Work @noahcoder11!
Yes, sure, that can be done. You kinda mean a book recommendation system!

**Comment by noahcoder11** [comment]
Yeah, that’s what I meant

Are you planning on setting up a backend and incorporating accounts so that people can put books in their “Cart” and have personalized recommendations?

**Comment by ParthJohri** [comment]
I was basically thinking of incorporating a ML model to suggest books, on the basis of their recent reads of genre!

**Comment by noahcoder11** [comment]
Alright, nice (I actually just contributed to an ML repository, that’s funny), are you planning to make a backend so that people can have accounts?

**Comment by ParthJohri** [comment]
Yes, but I'll have to learn backend for it!
It is a good suggestion :)

**Pull request merged**
