### PR TITLE
Added SignIn and SignUp page  issue#4

### PR DESCRIPTION
**Pull request by Kavyashah26**
Issue #4 
Created a new directory pages which contains login page. 
For testing purpose I have added redirection url as google.com and index page of website .
I hope this helps you. 

image
image

### CODE REVIEW

**Comment by ParthJohri** [comment]
Excellent work @Kavyashah26, could you also add the signup option in the index?

**Comment by Kavyashah26** [comment]
@ParthJohri  Can you please elaborate  more , I am not getting it !
I have already added option in navbar to login .
image

**Comment by ParthJohri** [comment]
Yep my bad, it wasn't visible at first, great work @Kavyashah26 thanks.

**Comment by Kavyashah26** [comment]
Okay , No issues 
Got my first PR merged and waiting for approval , very much excited as I am new to open source 😃 .
Looking forward to connect with you and share knowledge

**Pull request merged**
